spring:
  datasource:
    url: jdbc:postgresql://db.bnaltkyonbrpaxigwqdv.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Leo10messi!
    driver-class-name: org.postgresql.Driver
   
  
  jpa:
    hibernate:
      ddl-auto: none 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    connect-retries: 10
    init-sql: "SET statement_timeout = 0;"
  
  main:
    allow-bean-definition-overriding: true
  
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG
      com.sales.sample: DEBUG
      com.zaxxer.hikari: DEBUG
      org.flywaydb: DEBUG

salesapp:
  csv:
    file-path: classpath:sales_data.csv

app:
  data:
    file-path: classpath:sales_data.csv