spring:
  datasource:
    url: jdbc:postgresql://db.bnaltkyonbrpaxigwqdv.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Leo10messi!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG
      com.sales.sample: DEBUG
      com.zaxxer.hikari: DEBUG
salesapp:
  csv:
    file-path: classpath:sales_data.csv
app:
  data:
    file-path: classpath:sales_data.csv 
